# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Style/Lambda:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true
Layout/LeadingEmptyLines:
  Enabled: true
Layout/MultilineArrayBraceLayout:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Rails/Blank:
  Enabled: true
Rails/FilePath:
  Enabled: true
Rails/HttpStatus:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Style/Alias:
  Enabled: true
Style/EmptyMethod:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/RaiseArgs:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true
