# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true
  AutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
Layout/LeadingEmptyLines:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Rails/Blank:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HttpStatus:
  Enabled: false
Rails/RootPathnameMethods:
  Enabled: false
Style/Alias:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
